package builder

import "html/template"

var tmpl = template.Must(template.New("reset").Parse(templateStr))

const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by genenum.go

package {{.Package}}

import "fmt"

var names{{.Type}} = map[{{.Type}}]string{

}

func (v {{.Type}}) String() string {
    return names{{.Type}}[v]
}


{{range .Entries}} 
// {{.Name}}Error -
type {{.Name}}Error struct {
	Description string
}

func (v {{.Name}}Error) Error() string {
    return fmt.Sprintf("HTTP 429 %s", v.Description) 
}

func (v {{.Name}}Error) Alert() string {
    return "DDOS alert, call admins!"
} 

	{{end}}



`
