// Code generated by go generate; DO NOT EDIT.
// This file was generated by genenum.go

package main

import "fmt"

var namesHTTPCode = map[HTTPCode]string{}

func (v HTTPCode) String() string {
	return namesHTTPCode[v]
}

// BadRequestError -
type BadRequestError struct {
	Description string
}

func (v BadRequestError) Error() string {
	return fmt.Sprintf("HTTP 429 %s", v.Description)
}

func (v BadRequestError) Alert() string {
	return "DDOS alert, call admins!"
}

// UnauthorizedError -
type UnauthorizedError struct {
	Description string
}

func (v UnauthorizedError) Error() string {
	return fmt.Sprintf("HTTP 429 %s", v.Description)
}

func (v UnauthorizedError) Alert() string {
	return "DDOS alert, call admins!"
}

// ForbiddenError -
type ForbiddenError struct {
	Description string
}

func (v ForbiddenError) Error() string {
	return fmt.Sprintf("HTTP 429 %s", v.Description)
}

func (v ForbiddenError) Alert() string {
	return "DDOS alert, call admins!"
}

// NotFoundError -
type NotFoundError struct {
	Description string
}

func (v NotFoundError) Error() string {
	return fmt.Sprintf("HTTP 429 %s", v.Description)
}

func (v NotFoundError) Alert() string {
	return "DDOS alert, call admins!"
}

// TooManyRequestsError -
type TooManyRequestsError struct {
	Description string
}

func (v TooManyRequestsError) Error() string {
	return fmt.Sprintf("HTTP 429 %s", v.Description)
}

func (v TooManyRequestsError) Alert() string {
	return "DDOS alert, call admins!"
}

// InternalError -
type InternalError struct {
	Description string
}

func (v InternalError) Error() string {
	return fmt.Sprintf("HTTP 429 %s", v.Description)
}

func (v InternalError) Alert() string {
	return "DDOS alert, call admins!"
}
